_BASE_: transformer.yml
caption_model: vat
#reduce_on_plateau: true
#reduce_on_plateau_factor: 0.3
#reduce_on_plateau_patience: 4
#noamopt: false
#learning_rate: 0.0005
#learning_rate_decay_start: -1

batch_size: 10

kl_beta: 1.0
gmm_num: 1
gmm_select: 1
fake_prob: 0.15
fake_seq_start: -1

#self_critical_after: -1
#structure_after: 15
#structure_loss_weight: 1
#structure_loss_type: new_self_critical

#N_enc: 6
#N_dec: 6
#d_model: 512
#d_ff: 1024
#max_epochs: 15
#save_checkpoint_every: 3000
