_BASE_: transformer_vae_b8_l6.yml
caption_model: tfvae
reduce_on_plateau: false
reduce_on_plateau_factor: 0.75
reduce_on_plateau_patience: 3
noamopt: false
learning_rate: 0.000005
learning_rate_decay_start: -1

batch_size: 8

kl_beta: 1.0
gmm_num: 1
fake_prob: 0.15
fake_seq_start: -1

self_critical_after: -1
structure_after: 15
structure_loss_weight: 1
structure_loss_type: new_self_critical

N_enc: 4
N_dec: 6
d_model: 512
d_ff: 2048
max_epochs: 40
mp_level: O1
