_BASE_: transformer.yml
caption_model: tfvae
reduce_on_plateau: true
reduce_on_plateau_factor: 0.5
reduce_on_plateau_patience: 3
noamopt: false
learning_rate: 0.0000025
learning_rate_decay_start: -1

batch_size: 8

kl_beta: 0.5
gmm_num: 8
fake_prob: 0.15
fake_seq_start: -1

self_critical_after: -1
structure_after: 18
structure_loss_weight: 1
structure_loss_type: new_self_critical

N_enc: 4
N_dec: 6
d_model: 512
d_ff: 2048
max_epochs: 36
save_checkpoint_every: 4000

grad_clip_mode: norm
grad_clip_value: 1.0
